from google.appengine.ext import db
from google.appengine.ext import blobstore

class Cta(db.Model):
	Folio = db.IntegerProperty()
	Nombre = db.StringProperty()
	Apellidos = db.StringProperty()
	Puesto = db.StringProperty()
	Email = db.StringProperty()
	EmailAlt = db.StringProperty()
	Pass = db.StringProperty()
	Tel = db.StringProperty()
	Cel = db.StringProperty()
	FechaHora = db.DateTimeProperty()
	UsuarioInt = db.StringProperty()
	CodigoCfm = db.StringProperty()
	Status = db.BooleanProperty()

class Empresa(db.Model):
	IdEmp = db.StringProperty()
	Folio = db.IntegerProperty()
	RFC = db.StringProperty()
	Nombre = db.StringProperty()
	RazonSoc = db.StringProperty()
	DirCalle = db.StringProperty()
	DirCol = db.StringProperty()
	DirEnt = db.StringProperty()
	DirMun = db.StringProperty()
	DirCp = db.StringProperty()
	NumSuc = db.StringProperty()
	OrgEmp = db.StringProperty()
	OrgEmpOtro = db.StringProperty()
	OrgEmpReg = db.StringProperty()
	Url = db.StringProperty()
	Benef = db.IntegerProperty()
	PartLinea = db.IntegerProperty()
	ExpComer = db.IntegerProperty()
	#Desc = db.StringProperty(multiline=True)
	#Desc = db.StringProperty()
	Desc = db.TextProperty()
	FechaHora = db.DateTimeProperty()
	Status = db.BooleanProperty()

class Entidad(db.Model):
        CveEnt = db.StringProperty()
        Entidad  = db.StringProperty()
        Abrv = db.StringProperty()
        CveCap = db.StringProperty()
        Capital = db.StringProperty()
        Selected = db.StringProperty()

class Municipio(db.Model):
	CveEnt = db.StringProperty()
        Entidad = db.StringProperty()
        Abrv = db.StringProperty()
        CveMun = db.StringProperty()
        Municipio = db.StringProperty()
        CvaCab  = db.StringProperty()
        Cabecera = db.StringProperty()
        Selected = db.StringProperty()

class Sucursal(db.Model):
        IdSuc = db.StringProperty()
        IdEmp = db.StringProperty()
        Nombre = db.StringProperty()
        Tel = db.StringProperty()
        DirCalle = db.StringProperty()
        DirCol = db.StringProperty()
        DirEnt = db.StringProperty()
        DirMun = db.StringProperty()
        DirCp = db.StringProperty()
        GeoUrl = db.StringProperty()
        Geo1 = db.StringProperty()
        Geo2 = db.StringProperty()
        Geo3 = db.StringProperty()
        Geo4 = db.StringProperty()
        FechaHora = db.DateTimeProperty()
	Latitud = db.FloatProperty()
	Longitud = db.FloatProperty()

class Oferta(db.Model):
	IdOft = db.StringProperty()
	IdEmp = db.StringProperty()
	IdCat = db.IntegerProperty()
	Oferta = db.StringProperty()
	BlobKey = blobstore.BlobReferenceProperty(required=False, validator=None)
	#BlobKey = db.StringProperty()
	Empresa = db.StringProperty()
	Descripcion = db.TextProperty()
	Codigo = db.StringProperty()
	Precio = db.StringProperty()
	Descuento = db.StringProperty()
	Promocion = db.StringProperty()
	Enlinea = db.BooleanProperty()
	Url = db.StringProperty()
	Tarjetas = db.StringProperty()
	Meses = db.StringProperty()
	FechaHoraPub = db.DateTimeProperty()
	StatusPub = db.BooleanProperty()
	FechaHora = db.DateTimeProperty()

class OfertaSucursal(db.Model):
	IdOft = db.StringProperty()
	IdEmp = db.StringProperty()
	IdSuc = db.StringProperty()
	Sucursal = db.StringProperty()
	Lat = db.FloatProperty()
	Lng = db.FloatProperty()
        Empresa = db.StringProperty()
	Oferta = db.StringProperty()
	NOferta = db.StringProperty()
	Descripcion = db.TextProperty()
	NDescripcion = db.TextProperty
	Promocion = db.StringProperty()
	Precio = db.StringProperty()
        Descuento = db.StringProperty()
	Enlinea = db.BooleanProperty()
	Url = db.StringProperty()
	StatusPub = db.BooleanProperty()
	FechaHora = db.DateTimeProperty()

class Categoria(db.Model):
	IdCat = db.IntegerProperty()
	Categoria = db.StringProperty()

class OfertaPalabra(db.Model):
	IdEmp = db.StringProperty()
	IdOft = db.StringProperty()
	Palabra = db.StringProperty()
	FechaHora = db.DateTimeProperty()

class ChangeControl(db.Model):
        Id = db.StringProperty()
        Kind = db.StringProperty()
        Status = db.StringProperty()
        FechaHora = db.DateTimeProperty()

class SearchData(db.Model):
	Sid = db.StringProperty()
	Kind = db.StringProperty()
	Field = db.StringProperty()
	Value = db.StringProperty(multiline=True)
	FechaHora = db.DateTimeProperty()
	IdCat = db.IntegerProperty()
	Enlinea = db.BooleanProperty()

class OfertaEstado(db.Model):
	IdOft = db.StringProperty()
	IdEnt = db.StringProperty()

class ShortLogo(db.Model):
	Data = db.BlobProperty()
        IdEmp = db.StringProperty()
        IdImg = db.StringProperty()
        Kind = db.StringProperty()
        Name = db.StringProperty()
        Desc = db.TextProperty()
        Sizepx =  db.IntegerProperty()
        Sizepy =  db.IntegerProperty()
        Url = db.StringProperty()
        Type =  db.StringProperty()
        Sp1 = db.StringProperty()
        Sp2 = db.StringProperty()
        Sp3 = db.StringProperty()
        Sp4 = db.StringProperty()
        Np1 = db.IntegerProperty()
        Np2 = db.IntegerProperty()
        Np3 = db.IntegerProperty()
        Np4 = db.IntegerProperty()

class MvBlob(db.Model):
	FechaHora = db.DateTimeProperty()
	IdSuc = db.StringProperty()
	Blob = db.BlobProperty()
